services:

    jaguero.aboutme.listplugins_eventsubscriber:
        class: Jaguero\AboutmeBundle\Event\ListPluginsSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }
